### PR TITLE
cleanup context provider code smell

### PR DESCRIPTION
**Pull request by balibebas**
Address the code smell [I pointed out](https://github.com/AlexanderProd/gatsby-shopify-starter/pull/42/files#r440844459) in #42

### CODE REVIEW

**Comment by MaciekBaron** [comment]
You still haven't explained what exactly you're addressing here. Could you explain the change?

**Comment by balibebas** [comment]
https://sebastienlorber.com/handling-api-request-race-conditions-in-react

**Comment by MaciekBaron** [comment]
Buddy, instead of pointing me to URLs can you explain what you mean because I just tested your code and it has the same issue again that I fixed. I am wondering whether you understand what was done before or not?

**Comment by balibebas** [comment]
It removes the imperative code added and provides a means for adding a loading indicator for the cart. From a scale perspective the lib will allow for search with request cancelation (YAGNI for some). More info here: https://sebastienlorber.com/handling-api-request-race-conditions-in-react

**Comment by MaciekBaron** [comment]
image

I am getting this error again with your solution, so I am uncertain whether this actually adresses anything at all.

**Comment by balibebas** [comment]
I'm seeing the error. I need a little more time with this. Still learning hooks. Opened the PR to discuss but this lib doesn't seem to fit as well as I expected into the Provider model. If I get something working I'll update and reopen for discussion.

**Comment by balibebas** [comment]
Went back and tried to repro the error on Node 12 after a fresh clone of this repo and updating dependencies and was able to see the exact memory error you posted a total of once after rolling back the changes. My approach was to load up a bunch of pages in History then -- as quickly as possible -- move through history using the arrow keys. What about you? Are you using Node 12?

Without a reliable way to repoduce the error I cannot proceed. Though I did find another way to eliminate the code smell and that's to move the assignment inside the `useEffect` function scope and then use a clean-up function at the end `return () => { isRemoved = true }`.

**Comment by balibebas** [comment]
@MaciekBaron Went back and tried to repro the error on Node 12 after a fresh clone of this repo and updating dependencies and was able to see the exact memory error you posted a total of once after rolling back the changes. My approach was to load up a bunch of pages in History then -- as quickly as possible -- move through history using the arrow keys. What about you? Are you using Node 12?

Without a reliable way to repoduce the error I cannot proceed. Though I did find another way to eliminate the code smell and that's to move the assignment inside the `useEffect` function scope and then use a clean-up function at the end `return () => { isRemoved = true }`.

**Comment by balibebas** [comment]
@MaciekBaron Went back and tried to repro the error on Node 14.4.0 after a fresh clone of this repo and updating dependencies and was able to see the exact memory error you posted a total of once after rolling back the changes. My approach was to load up a bunch of pages in History then -- as quickly as possible -- move through history using the arrow keys. What about you? Are you using Node 14?

Without a reliable way to repoduce the error I cannot proceed. Though I did find another way to eliminate the code smell and that's to move the assignment inside the `useEffect` function scope and then use a clean-up function at the end `return () => { isRemoved = true }`.

**Comment by MaciekBaron** [comment]
I think the memory leak issue exists also [on the product page](https://github.com/AlexanderProd/gatsby-shopify-starter/blob/eaba8b8702372ade16a81c68243c1bd8082cfb40/src/components/ProductForm/index.js#L26) - is that were you see the issue?

**Comment by balibebas** [comment]
Yep do see that one more frequently. If that's the same error I can go on that. There's another memory leak on Cart too when the last product is removed due to the subcomponent `lineItems` map. Have you seen that one?

**Pull request closed without merging**
